# syntax=docker/dockerfile:1
FROM golang:1.22.0-alpine

RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY . /app/

RUN mv db /db 
RUN chown -R trainee:mercari /db

RUN go mod tidy
CMD go run app/main.go